# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: adivino.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'adivino.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\radivino.proto\"#\n\x0fPreguntaRequest\x12\x10\n\x08pregunta\x18\x01 \x01(\t\"$\n\x0fPrediccionReply\x12\x11\n\trespuesta\x18\x01 \x01(\t2<\n\x07\x41\x64ivino\x12\x31\n\tPreguntar\x12\x10.PreguntaRequest\x1a\x10.PrediccionReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adivino_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREGUNTAREQUEST']._serialized_start=17
  _globals['_PREGUNTAREQUEST']._serialized_end=52
  _globals['_PREDICCIONREPLY']._serialized_start=54
  _globals['_PREDICCIONREPLY']._serialized_end=90
  _globals['_ADIVINO']._serialized_start=92
  _globals['_ADIVINO']._serialized_end=152
# @@protoc_insertion_point(module_scope)
