# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import adivino_pb2 as adivino__pb2

GRPC_GENERATED_VERSION = '1.72.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in adivino_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdivinoStub(object):
    """definicion de servicio
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Preguntar = channel.unary_unary(
                '/Adivino/Preguntar',
                request_serializer=adivino__pb2.PreguntaRequest.SerializeToString,
                response_deserializer=adivino__pb2.PrediccionReply.FromString,
                _registered_method=True)


class AdivinoServicer(object):
    """definicion de servicio
    """

    def Preguntar(self, request, context):
        """cliente hace pregunta y recibe prediccion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdivinoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Preguntar': grpc.unary_unary_rpc_method_handler(
                    servicer.Preguntar,
                    request_deserializer=adivino__pb2.PreguntaRequest.FromString,
                    response_serializer=adivino__pb2.PrediccionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Adivino', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Adivino', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Adivino(object):
    """definicion de servicio
    """

    @staticmethod
    def Preguntar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Adivino/Preguntar',
            adivino__pb2.PreguntaRequest.SerializeToString,
            adivino__pb2.PrediccionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
